stocks:
  api:
    fqdn: https://latest-stock-price.p.rapidapi.com

spring:
  profiles:
    active: local
    jackson:
      default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# actuators
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, mappings